### ISSUE TITLE
Errors for restrictions

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/model2owl#62]
in the OWL restriction file (version at 13 November), there are a lot of Errors. They are typically due to restrictions definitions.

See the following screenshot of my Protégé.
<img width="1214" alt="Screen Shot 2020-11-23 at 17 27 08" src="https://user-images.githubusercontent.com/24624577/99987803-2b121a00-2db1-11eb-8a76-aa06971f2fd9.png">

**Comment by costezki** [comment]
caused by empty restrictions.

**Comment by costezki** [comment]
fixed

**Comment by giorgialodi** [comment]
This situation still persists so I would reopen this issue. I am looking at the version of December 01 of the OWL restrictions file. This is what I see if I load the rdf file in Protégé
<img width="1206" alt="Screen Shot 2020-12-02 at 13 06 33" src="https://user-images.githubusercontent.com/24624577/100870740-67273800-349f-11eb-84d2-2071170363f9.png">

**Comment by costezki** [comment]
this is strange, will check again.

**Comment by Dragos0000** [comment]
This was fixed a week ago.

**Comment by giorgialodi** [comment]
Sorry @Dragos0000 but we discussed yesterday with @costezki on this issue that it is still present, as Eugen was able to see from yesterday's discussion. You can also notice it from the screenshot above of the version 01 December produced after your fixes.

**Comment by giorgialodi** [comment]
I will try to investigate which are the restrictions that cause the errors and try to help you further.

**Comment by giorgialodi** [comment]
In version 07/12 of the OWL restriction file this issue is no longer present.
